---
#
# Ansible managed
#
repository:
  description: Install and configure jitsi on your system.
  homepage: https://buluma.github.io/
  topics: jitsi, ansible, molecule, tox, playbook, hacktoberfest
